### ISSUE TITLE
Graphics for Docs - DO NOT EDIT

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/Docs#1]
![page-rendering-680x223](https://user-images.githubusercontent.com/1865400/28495584-5cccb5ea-6eed-11e7-99ff-ba2b5a227e8b.png)

**Comment by kellishouts** [comment]
![page-setup](https://user-images.githubusercontent.com/1865400/28495696-2ddafaa2-6ef3-11e7-989d-fdd5a644800a.png)

**Comment by kellishouts** [comment]
![page-template-about](https://user-images.githubusercontent.com/1865400/28495841-061792e2-6ef7-11e7-8882-a38d050eace5.png)
![page-template-about-new](https://user-images.githubusercontent.com/1865400/28495840-0616a706-6ef7-11e7-8ffc-c344fdd8b6ee.png)

**Comment by kellishouts** [comment]
![page-template-about-browser](https://user-images.githubusercontent.com/1865400/28495755-daa33442-6ef4-11e7-9712-7fef3db36fe9.png)

**Comment by kellishouts** [comment]
![collection-template-dir-new](https://user-images.githubusercontent.com/1865400/28496727-333ffa5e-6f0e-11e7-89ab-2556e74ac5e2.png)
![collection-template-dir](https://user-images.githubusercontent.com/1865400/28496728-33406c5a-6f0e-11e7-8b37-96d704d52e75.png)

**Comment by kellishouts** [comment]
My First Page

![page-setup](https://user-images.githubusercontent.com/1865400/28547380-4a2518c8-706a-11e7-8a9c-2652b4752009.png)
![page-edit](https://user-images.githubusercontent.com/1865400/28547379-4a21a35a-706a-11e7-875b-1b317bdf5185.png)
![first-site-wider](https://user-images.githubusercontent.com/1865400/28547862-9d65786e-706c-11e7-9bc2-bc989dae7299.png)

**Comment by kellishouts** [comment]
<img width="26" alt="wrench" src="https://user-images.githubusercontent.com/1865400/28548077-afe52966-706d-11e7-93f0-ce9e958ec070.png">

<img width="27" alt="pencil" src="https://user-images.githubusercontent.com/1865400/28548078-afea5594-706d-11e7-99e6-4d023d4bca84.png">

**Comment by kellishouts** [comment]
<img width="236" alt="homepage" src="https://user-images.githubusercontent.com/1865400/28551369-461a3f38-7083-11e7-9a81-f11bd7cd80f1.png">

<img width="683" alt="homepage-page-rendering" src="https://user-images.githubusercontent.com/1865400/28551396-738c3188-7083-11e7-98a4-5d05b7b0b516.png">

<img width="730" alt="homepage-fields" src="https://user-images.githubusercontent.com/1865400/28551419-9acdbd52-7083-11e7-8d57-044e65404628.png">

**Comment by kellishouts** [comment]
<img width="459" alt="elements-collection-setup" src="https://user-images.githubusercontent.com/1865400/28551508-1b842256-7084-11e7-9937-8ac2629977d6.png">
<img width="720" alt="elements-collection-settings" src="https://user-images.githubusercontent.com/1865400/28551522-30d3c5a8-7084-11e7-9ecf-db23a76f36f0.png">
<img width="697" alt="elements-collection-fields" src="https://user-images.githubusercontent.com/1865400/28551551-571e8a4a-7084-11e7-88bc-b9ff2524654d.png">
<img width="359" alt="elements-collection-primary-label" src="https://user-images.githubusercontent.com/1865400/28551566-70836c26-7084-11e7-979e-09429ea071b9.png">

<img width="916" alt="airship-admin-login" src="https://user-images.githubusercontent.com/1865400/28551593-a1a45e82-7084-11e7-9272-c10b25aedae3.png">

<img width="683" alt="airship-schema" src="https://user-images.githubusercontent.com/1865400/28551616-d3c1d764-7084-11e7-87b2-652de63df8e5.png">

<img width="625" alt="page-field-body" src="https://user-images.githubusercontent.com/1865400/28551639-00242dca-7085-11e7-9cf0-74fa34527306.png">

<img width="901" alt="all-pages" src="https://user-images.githubusercontent.com/1865400/28551652-1e438152-7085-11e7-86d8-ae265fefc654.png">

<img width="604" alt="elements-collection-setup" src="https://user-images.githubusercontent.com/1865400/28551733-970e3e4c-7085-11e7-8caf-af062a493fe3.png">

**Comment by kellishouts** [comment]
![open-sublime](https://user-images.githubusercontent.com/1865400/28698994-97c1f0c2-72e2-11e7-9ecf-25cc0c9d9cb9.png)

![edit-root](https://user-images.githubusercontent.com/1865400/28699019-c3912dda-72e2-11e7-9787-86059fcc542c.png)

**Comment by kellishouts** [comment]
![help-root](https://user-images.githubusercontent.com/1865400/28699367-c7d8e75a-72e4-11e7-916b-271a62b36cd8.png)

**Comment by kellishouts** [comment]
![articles-collection](https://user-images.githubusercontent.com/1865400/28703286-cef5e7ee-72fe-11e7-982e-cf7ad896dc6b.png)

![delete-collection](https://user-images.githubusercontent.com/1865400/28703307-ecadaede-72fe-11e7-8985-2ad9a1c881b0.png)

![confirm-delete-collection](https://user-images.githubusercontent.com/1865400/28703311-fd539776-72fe-11e7-8292-dbd588f845f2.png)

**Comment by kellishouts** [comment]
![demo-page](https://user-images.githubusercontent.com/1865400/28703362-56aa7844-72ff-11e7-910e-b0d69899fa28.png)

![uneditable-fields](https://user-images.githubusercontent.com/1865400/28703393-7f098f50-72ff-11e7-9ac1-ed4cb1cf0d11.png)

**Comment by kellishouts** [comment]
![thumbnails](https://user-images.githubusercontent.com/1865400/28706552-857d5b9e-7310-11e7-814f-dc55014b9c78.png)

![sitemap](https://user-images.githubusercontent.com/1865400/28704107-27985f58-7304-11e7-9593-db9734f8046e.png)

**Comment by maliaoreta** [comment]
![modified_homepage_fields](https://user-images.githubusercontent.com/16835553/28737399-0342c644-738a-11e7-8b96-2b024592eba6.png)

<img width="27" alt="grey-pencil" src="https://user-images.githubusercontent.com/16835553/28738624-2d7928f8-7390-11e7-9993-61a68b2844ae.png">

**Comment by kellishouts** [comment]
![wireframes](https://user-images.githubusercontent.com/1865400/28741053-27b5a33c-73aa-11e7-9bc1-94b9989c2ec4.jpg)
![sitemap](https://user-images.githubusercontent.com/1865400/28741054-27d16e00-73aa-11e7-8140-1cd2493d9424.jpg)

**Comment by kellishouts** [comment]
![image](https://user-images.githubusercontent.com/1865400/28741262-25d965e0-73ae-11e7-84b5-aeeff2b239e1.png)

**Comment by kellishouts** [comment]
![related-news](https://user-images.githubusercontent.com/1865400/28741348-fa676a7c-73af-11e7-81d3-3e82ffcec6d1.jpg)

**Comment by kellishouts** [comment]
![news-on-homepage](https://user-images.githubusercontent.com/1865400/28741384-c0e70522-73b0-11e7-995c-52aabedb334b.jpg)

**Comment by kellishouts** [comment]
![primary-label](https://user-images.githubusercontent.com/1865400/29060439-805c424e-7bb5-11e7-94df-29c382b55dd1.png)
![post-fields](https://user-images.githubusercontent.com/1865400/29060442-806f825a-7bb5-11e7-9397-a5d28f5cba0c.png)
![post-example](https://user-images.githubusercontent.com/1865400/29060443-807042bc-7bb5-11e7-8c9b-811b61d48186.png)
![collection-setup](https://user-images.githubusercontent.com/1865400/29060441-806f6dd8-7bb5-11e7-99cf-f7ad80740e4d.png)
![collection-settings](https://user-images.githubusercontent.com/1865400/29060440-8060e506-7bb5-11e7-906d-aa2abbcccf5d.png)
![collection-id](https://user-images.githubusercontent.com/1865400/29060438-805c1918-7bb5-11e7-8030-0488b826b0ee.png)
![bcc-publicmakesetting](https://user-images.githubusercontent.com/1865400/29060444-8078786a-7bb5-11e7-86ce-3d953ef88e52.png)
![submission-example](https://user-images.githubusercontent.com/1865400/29060885-5a3a62d8-7bb7-11e7-92cf-ef0b37837be7.png)

![email-name](https://user-images.githubusercontent.com/1865400/29061827-20c8b366-7bbb-11e7-804c-3c22d4cadbe4.png)

**Comment by kellishouts** [comment]
![contact-page](https://user-images.githubusercontent.com/1865400/29060965-a47f227a-7bb7-11e7-88dc-10880e1ebf92.png)

**Comment by kellishouts** [comment]
![image](https://user-images.githubusercontent.com/1865400/29198508-49fc5e46-7de0-11e7-92f2-23766826a943.png)

![image](https://user-images.githubusercontent.com/1865400/29198518-64bd7b5c-7de0-11e7-8089-c4cfc06ef2fd.png)

![image](https://user-images.githubusercontent.com/1865400/29198548-bda9295a-7de0-11e7-988d-afea5aea6367.png)

![image](https://user-images.githubusercontent.com/1865400/29198585-22dea534-7de1-11e7-85b2-550835e82a04.png)

![image](https://user-images.githubusercontent.com/1865400/29198607-51969cc4-7de1-11e7-9fdd-2be1c1b08cbd.png)

![image](https://user-images.githubusercontent.com/1865400/29198681-ef17b3e8-7de1-11e7-82ad-1597472098ef.png)

**Comment by kellishouts** [comment]
![secure-the-skies](https://user-images.githubusercontent.com/1865400/29244662-65b2a5bc-7f59-11e7-9c46-cc5d61d94ea3.jpg)

**Comment by kellishouts** [comment]
![the-skies-are-secured](https://user-images.githubusercontent.com/1865400/29494711-159f8a42-854c-11e7-8abd-9db216c51f3d.jpg)

**Comment by kellishouts** [comment]
![all-green](https://user-images.githubusercontent.com/1865400/29494812-dd80d790-854d-11e7-87a5-29e14f2f9ab6.png)
![mixed-content](https://user-images.githubusercontent.com/1865400/29494813-dda162a8-854d-11e7-91c4-8dd7c857443a.png)

**Comment by kellishouts** [comment]
<img width="919" alt="new-site" src="https://user-images.githubusercontent.com/1865400/29646158-83a21ac2-881d-11e7-9a49-83877733ffc1.png">

**Comment by kellishouts** [comment]
<img width="504" alt="new-site-small" src="https://user-images.githubusercontent.com/1865400/29646477-64891a26-881f-11e7-9024-170c1249e4af.png">

**Comment by kellishouts** [comment]
<img width="507" alt="sublime" src="https://user-images.githubusercontent.com/1865400/29646613-46c1b01a-8820-11e7-9484-26327303bac3.png">

**Comment by kellishouts** [comment]
![sublime](https://user-images.githubusercontent.com/1865400/29646676-98367020-8820-11e7-81c8-4f4f92e9eb9f.jpg)

**Comment by kellishouts** [comment]
<img width="847" alt="airshipcms" src="https://user-images.githubusercontent.com/1865400/29646793-36ffe1e6-8821-11e7-9e7a-b14379517277.png">

**Comment by kellishouts** [comment]
<img width="505" alt="new-teal" src="https://user-images.githubusercontent.com/1865400/29646934-27ce4f72-8822-11e7-9987-d71940dd6a74.png">

**Comment by kellishouts** [comment]
![new-teal](https://user-images.githubusercontent.com/1865400/29647018-8cb91908-8822-11e7-8664-b284a7def4f5.jpg)

**Comment by kellishouts** [comment]
![download](https://user-images.githubusercontent.com/1865400/30157261-83e051de-935d-11e7-85b0-65ea34a405b7.png)

**Comment by kellishouts** [comment]
![download](https://user-images.githubusercontent.com/1865400/30157575-653b8d1a-935e-11e7-812a-06561cb45cd5.jpg)
